services:
  backend:
    build: ./backend
    ports:
      - "8080"
    environment:
      - PORT=8080

  frontend:
    build: ./frontend
    ports:
      - "80"
    environment:
      - BACKEND_URL=ws://nginx/ws

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
